### ISSUE TITLE
@cccs-rs : TagCheck service fails for the submitted file. Any reasons?

### ISSUE THREAD

**Issue by dhruvpatel56** [CybercentreCanada/assemblyline-service-yara#42]

**Comment by dhruvpatel56** [comment]
@cccs-rs 
Please let me know any reason why TagCheck service can get failed for the submitted files.
Thanks!

**Comment by cccs-rs** [comment]
Current development and stable images don't appear to fail on the files given. Is there any specific files it seems to fail on or is there an exception message in the service output?

**Comment by dhruvpatel56** [comment]
Hi there,
Thank you for your reply!

It seems to fail all the submitted files.
Sometimes, I see both TagCheck/Yara services failed too.

Thanks!

**Comment by merfin993** [comment]
Hi, i have the same problem with a fresh installation of assemblyine.

Currently i use a test file "pafish64.exe" and also some emotet samples.(the pafish file uses several anti-vm tricks and are detected by the yara rules)
Yara always returns an empty result, just in case you analyze pcap then yara seems to work.
And if u try to analyze pcap Suricata doesn't work either.

Thanks

**Comment by dhruvpatel56** [comment]
Here's the hash file:
SHA 256: b1b7f42619abccfcc5b3feb119a7cdcb7a32123438f20b942c9dc889b9b0adc9

This is the screenshot of the services failing:
Not sure why these services are failing. Do you know what could be an issue?

Thanks!

**Comment by cccs-rs** [comment]
> Hi, i have the same problem with a fresh installation of assemblyine.
> 
> Currently i use a test file "pafish64.exe" and also some emotet samples.(the pafish file uses several anti-vm tricks and are detected by the yara rules) Yara always returns an empty result, just in case you analyze pcap then yara seems to work. And if u try to analyze pcap Suricata doesn't work either.
> 
> Thanks

An empty result isn't so much an error as it is the service didn't detect anything. 

In this case, it can be due to Assemblyline not having any YARA rules that can detect on this piece of malware. However, if you have or know of YARA rules that should be able to detect on this file, you are able to add them to the system as a signature source.

Suricata is similar to YARA & TagCheck in which they depend on signature detection rules in order to flag information about a file; if they don't have any rules that would match, then it will produce an empty result.

**Comment by merfin993** [comment]
> > Hi, i have the same problem with a fresh installation of assemblyine.
> > Currently i use a test file "pafish64.exe" and also some emotet samples.(the pafish file uses several anti-vm tricks and are detected by the yara rules) Yara always returns an empty result, just in case you analyze pcap then yara seems to work. And if u try to analyze pcap Suricata doesn't work either.
> > Thanks
> 
> An empty result isn't so much an error as it is the service didn't detect anything.
> 
> In this case, it can be due to Assemblyline not having any YARA rules that can detect on this piece of malware. However, if you have or know of YARA rules that should be able to detect on this file, you are able to add them to the system as a signature source.
> 
> Suricata is similar to YARA & TagCheck in which they depend on signature detection rules in order to flag information about a file; if they don't have any rules that would match, then it will produce an empty result.

thank you for your reply, in suricata there is just an error as you can see, I have already created an issues in the correct repo.
![Screenshot from 2022-07-04 14-28-54](https://user-images.githubusercontent.com/108698184/177318310-7553cfb4-a829-45ac-b990-b4b3f5670928.png)

As for yara, there is a problem.
With the "Wait for a valid update before starting service" flag set to yes the container does not start.
The yara rules are there because they work with pcaps but don't work for executables (for now I have only tested those and pcaps).
"pafish.exe" is not malware.
is a program to check that the environment (sandbox) in which you want to analyze the samples is not detected.
It can also be used to check if yara rules work, as it was detected in previous assemblyline versions with more than 10 flags.
It is detected due to the anti-vm techniques it uses.
I ask you if you can kindly provide me a sample which you are sure trigger yara rules, because all the executables I am testing give me the same result.

**Comment by cccs-rs** [comment]
> thank you for your reply, in suricata there is just an error as you can see, I have already created an issues in the correct repo. ![Screenshot from 2022-07-04 14-28-54](https://user-images.githubusercontent.com/108698184/177318310-7553cfb4-a829-45ac-b990-b4b3f5670928.png)

This is definitely a bug in the Suricata service so that I can address.

> ...
 I ask you if you can kindly provide me a sample which you are sure trigger yara rules, because all the executables I am testing give me the same result.

Sample from VirusTotal: [2ed2fef9bdae1f9de8303453b978f20cbdb1bcbe3d29191b4b965daff5181799](https://www.virustotal.com/gui/file/2ed2fef9bdae1f9de8303453b978f20cbdb1bcbe3d29191b4b965daff5181799)
With default ruleset (in particular from BartBlaze), you should have two rule hits:
![image](https://user-images.githubusercontent.com/62077998/177330991-3deafa05-f7c0-4402-a6e2-c5494676c45b.png)

**Comment by cccs-rs** [comment]
> Does AL4 not detecting anything for .exe files?

This depends on what services are loaded into the Assemblyline instance. 
Some services provide information about the file whereas others perform detection.

You can read more about Assemblyline here:
https://cybercentrecanada.github.io/assemblyline4_docs/overview/how_it_works/

**Comment by dhruvpatel56** [comment]
Thanks!
Question regarding Yara service:

Once I add new Yara rule set within Signature source via UI, do I need to
make any config changes or anything else?

Thanks!

**Comment by cccs-jp** [comment]
Hi there, Assemblyline has a set of heuristic for exe files which comes from the PE service. However identifying malicious .exe is often done with signatures or behavior. So a good set of Yara signature, anti-virus and sandbox will provide much stronger results!

Once you add a signature source to the UI, the signature should load automatically, you can change how often it pull in the service config to make it happen quicker.  If nothing show up see the updater logs to see if there was any problem with you specific rule source configuration.

**Comment by dhruvpatel56** [comment]
Hi there,
Another quick question:
Does Yara service have any by default dependencies?
I am asking this because I do see one in my AL4 but Service Management "
doc doesn't show one.

Thanks!

**Comment by cccs-jp** [comment]
I'm not sure what you mean here. Can you clarify? Also you can reach out to the team via Discord here: https://discord.gg/GUAy9wErNu  Seems like your questions would be easier to answer there.

**Comment by cccs-rs** [comment]
> Hi there, Another quick question: Does Yara service have any by default dependencies? I am asking this because I do see one in my AL4 but Service Management " doc doesn't show one.

Yes the service does. It has a dependency for fetching signatures which was a significant change since when the documentation was created for that section.

**Comment by dhruvpatel56** [comment]
Perfect!
Thanks!

I have added couple of Yara signature sources, but I only see bartblaze and
reversinglabs signatures deployed in "Signature" tab under Manage on UI.

I have added those signature sources details in service _menifest.yml file
in assembly-service-yara got repo which is cloned within AL4.
Do I need to make any other changes in order for those newly added sources
to be deployed?

Thanks!

**Comment by cccs-jp** [comment]
signatures sources should be added/modified under manage > Signature sources. no yml file changes are required. If they dont show up you might need to look at the updater container logs.

**Comment by cccs-rs** [comment]
Closing stale issue.

**Comment by cccs-rs** [comment]
If this message has only appeared once or a few times, it usually indicates that the index associated to the service_delta hasn't been created yet. So it will keep retrying the operation until the index is present and ready.

Considering that this message is dated several months ago, I assume this message isn't reoccurring more recently?
